#! /bin/bash
version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/VERSION | grep '^\+[0-9]' | sed 's/[^0-9\.]//g'`

if [ "$version" != "" ]; then
    git tag -a "v$version" -m ""
    if [ $? -eq 0]; then
        echo "Tagged your commit as v$version"
    else
        echo "The commit succeeded but tagging failed. Please contact Jon Lim at jlim7@comcast.net."
fi
